### ISSUE TITLE
Failure to build the latest version

### ISSUE THREAD

**Issue by Seelik0** [CNA-Bld/CarrotJuicer#7]
I get an error when trying to build v1.7.1 using Visual Stadio 2022.

`Error		building minhook:x64-windows-static failed with: BUILD_FAILED	CarrotJuicer	C:\Users\Username\source\repos\CarrotJuicer\CarrotJuicer\EXEC	1
Error	MSB3073	The command ""C:\Users\Username\source\repos\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\Users\Username\source\repos\vcpkg\\" "--x-manifest-root=C:\Users\Username\source\repos\CarrotJuicer\\" "--x-install-root=C:\Users\Username\source\repos\CarrotJuicer\vcpkg_installed\x64-windows-static\\" " exited with code 1.	CarrotJuicer	C:\Users\Username\source\repos\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	183`

Before this, x-block-origin blocked me from downloading the files minhook-cmake-support.patch and minhook-cmake-support-5f353b16.patch.

I don't know how to disable x-block-origin so I downloaded the file manually and placed the file I just mentioned in C:\Users\Username\source\repos\vcpkg\downloads

**Comment by Seelik0** [comment]
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:22 (message):
  

  File does not have expected hash:

          File path: [ C:/Users/Username/source/repos/vcpkg/downloads/minhook-cmake-support-5f353b16.patch ]
      Expected hash: [ 5f353b167e2c31e5e06258420c78fbae0095368cf687ff06a350d6b69b30476824785dde5dbcea3e30ff827e7cdb293727a73e6b1e6875f00aa891b2980c3877 ]
        Actual hash: [  ]

  The cached file SHA512 doesn't match.  The file may have been corrupted.
  To re-download this file please delete cached file at path
  C:/Users/Username/source/repos/vcpkg/downloads/minhook-cmake-support-5f353b16.patch
  and retry.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:192 (z_vcpkg_download_distfile_test_hash)
  buildtrees/versioning_/versions/minhook/fea414bee13115e201fe93699ba5b55c7ae031b8/portfile.cmake:12 (vcpkg_download_distfile)
  scripts/ports.cmake:192 (include)

**Comment by LunaireVT** [comment]
Where did you download the files from? I'm having the same issue.
